[tox]
requires = tox>=4
envlist = ruff,bandit,black,doc8,sphinx-build

[testenv]
package = skip
use_current_env = true

[testenv:black]
commands = black --check {posargs:source}
allowlist_externals = black

[testenv:ruff]
commands = ruff check {posargs:source}
allowlist_externals = ruff

[testenv:bandit]
commands = bandit -r {posargs:source}
allowlist_externals = bandit

[testenv:doc8]
commands = doc8 {posargs:source}
allowlist_externals = doc8

[testenv:sphinx-build]
commands = sphinx-build -n -W -b html source build
allowlist_externals = sphinx-build
